site_name: progress4j
site_url: https://www.progress4j.org

repo_url: https://github.com/mikehearn/progress4j
repo_name: mikehearn/progress4j

# Current version from git tag
extra:
  version:
    provider: mike

nav:
  - Introduction: index.md
  - Quickstart: quickstart.md
  - JSON Format: json.md
  - API Documentation:
    - Javadoc (API Module): javadoc/index.html
    - Dokka (Full): dokka/index.html

theme:
  name: 'material'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - toc.integrate

  palette:
    - scheme: default
      primary: 'black'
      accent: 'grey'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Titillium Web
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables

plugins:
  - search
