name: Deploy Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate Documentation
        run: |
          ./gradlew prepareAllDocs
      - name: Install dependencies
        run: |
          cd docs
          pip install mkdocs-material
      - name: Deploy docs
        run: |
          cd docs
          mkdocs gh-deploy --force
